coverage:
    status:
        project:
            default:
                target: auto
                threshold: 0.15%
                base: auto
                paths:
                    - "src"
        patch:
            default:
                target: auto
                threshold: 3%

flag_management:
    default_rules:
        carryforward: true
